server:
  port: 8082

spring:
  application:
    name: ecommerce-payment
  boot:
    run:
      jvmArguments: --add-opens java.base/java.util=ALL-UNNAMED
  kafka:
    bootstrap-servers: http://localhost:9092

kafka:
  topic:
    name: e-commerce
  group-id: payment-processing-group