services:
  dashboard-frontend:
    build:
      context: .
      dockerfile: DashboardFrontendDockerFile
    volumes:
      - ./dashboard-frontend:/app
    ports:
      - '4200:4200'
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true