spring:
  application:
  name: ecommerce hexagonal

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/e-commerce
    username: myuser
    password: password
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092

kafka:
  topic:
    name: e-commerce
  group-id:
    create-order: ecommerce-create-order-group
    check-offer: ecommerce-check-offer-group
    evaluate-offer: ecommerce-evaluate-offer-group
    apply-offer: ecommerce-apply-group
    process-payment: ecommerce-process-payment
    success-payment: ecommerce-success-payment
    ship-order: ecommerce-ship-order
    deliver-order: ecommerce-deliver-order