server:
  port: 8081

spring:
  application:
    name: Rule Engine
  boot:
    run:
      jvmArguments: --add-opens java.base/java.util=ALL-UNNAMED

  kafka:
    bootstrap-servers: http://localhost:9092

kafka:
  topic:
    name: e-commerce
  group-id: order-processing-group