package com.rage.ecommerce.drools.rules.premium

import com.rage.ecommerce.drools.domain.model.Offer;
import com.rage.ecommerce.drools.domain.model.enums.CustomerSubscription;
import com.rage.ecommerce.drools.domain.model.Decision;
import java.time.LocalDate;
import java.time.Period;

rule "PremiumRule02"
when
    $offer : Offer(
        getSubscription() == CustomerSubscription.PREMIUM,
        getDateOfBirth() != null,
        $age : Period.between(getDateOfBirth(), LocalDate.now()).getYears()
        )
        eval( $age > 30 )
then
    System.out.println("Premium Rule fired for customer with age greater than 30: " + $age);
    Decision decision = new Decision();
    decision.setOfferRate(20.0);
    decision.setReason("20% offer can be applied as the customer has premium subscription, and is greater than 30");
    insert(decision);
end