version: '3.8'

services:
  node-angular:
    image: node:20
    container_name: angular-dev-container
    volumes:
      - ../..:/app
      - /app/node_modules

    working_dir: /app
    restart: unless-stopped
    ports:
      - "4200:4200"
    command: tail -f /dev/null